# Generated by Django 6.0.3 on 2026-03-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(max_length=500, verbose_name='Опис')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Дебет'), ('CREDIT', 'Кредит')], default='DEBIT', max_length=6, verbose_name='Тип')),
            ],
        ),
    ]
